---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    monitoring: prometheus
...
---
apiVersion: v1
kind: Namespace
metadata:
  name: operator
  labels:
    monitoring: prometheus
...
