apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crd
  namespace: argocd
  labels:
    app: prometheus-operator
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: 14.0.0
    chart: "prometheus-operator-crds"
    helm: 
      releaseName: "prometheus-operator-crds"
  destination:
    server: https://kubernetes.default.svc
    namespace: operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=ture
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    - Replace=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 4m
  revisionHistoryLimit: 10
