apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  labels:
    app: prometheus-operator
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://prometheus-community.github.io/helm-charts"
    targetRevision: 63.1.0 
    chart: "kube-prometheus-stack"
    helm: 
      releaseName: "kube-prometheus-stack"
      skipCrds: true
      values: |
        prometheus:
          prometheusSpec:
            - url: remoteWrite: "http://kube-prometheus-stack-prometheus.kube-prometheus-stack-mimir-ingester-zone-a:9095/metrics"
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-prometheus-stack
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - Validate=ture
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 4m
  revisionHistoryLimit: 10
