apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mimir
  namespace: argocd
spec:
  destination:
    namespace: mimir
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: 'https://github.com/dtibor/prometheustest'
    targetRevision: HEAD
    path: apps/mimir
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
